name: deploy-app

on:
  push:
    branches:
      - main
      - feature-deploy
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying the app..."

